version: "3.8"

services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=file_ingestion
    ports:
      - "3306:3306"
    volumes:
      - mysql:/etc/mysql/conf.d
    networks:
      - app-network
  file-ingestion-api:
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/file_ingestion
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql:

networks:
  app-network:
    driver: bridge